# Generated by Django 4.2.3 on 2023-07-13 01:41

from django.db import migrations

def populate_status(apps, schema_editor):
    entries = {
        'draft': 'An unpublished post, not yet complete',	
        'published': 'A post that appears on the site',
        'archived': 'An archived post, not visible to end users'
    }
    Status = apps.get_model('posts', 'Status')
    for name, desc in entries.items():
        status_obj = Status(name=name, description=desc)
        status_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_status),
    ]
